export { default as NavBar } from "./NavBar/NavBar";
export { default as MangaSlider } from "./MangaSlides/MangaSlider";
export { default as MangaTable } from "./MangaTable/MangaTable";
export { default as ReadHistory } from "./ReadHistory/ReadHistory";
export { default as SuggestionSlider } from "./SuggestionSlider/SuggestionSlider";
export { default as Footer } from "./Footer/Footer";
export { MangaTable2 } from "./MangaTable/MangaTable";
export { GetTable } from "./MangaTable/MangaTable";
export { default as Paths } from "./Paths/Paths";
export { default as Pagination } from "./Pagination/Pagination";
export { default as QuickMangaSlider } from "./QuickMangaSlider/QuickMangaSlider";
export { default as Dropzone } from "./Dropzone/Dropzone";
export { default as CommentSec } from "./CommentSec/CommentSec";
export { default as MetaDecorator } from "./MetaDecorator/MetaDecorator";
